#!/usr/bin/env python3
import argparse
import json
import math
import os
from pathlib import Path

import numpy as np
from scipy.optimize import least_squares
from isaacsim import SimulationApp

app = SimulationApp({"headless": True})

import omni
from isaacsim.core.api import World
from isaacsim.core.prims import Articulation, RigidPrim
from isaacsim.core.utils.stage import open_stage
from pxr import Gf, Usd, UsdGeom


ROBOT = os.environ.get("ROBOT_PRIM_PATH", "/World/Robot")
JOINTS = f"{ROBOT}/joints"
LEFT_WRIST = "/World/Robot/left_link6"
LEFT_FINGER_A = "/World/Robot/left_link7"
LEFT_FINGER_B = "/World/Robot/left_link8"
LEFT_ARM_JOINT_NAMES = [f"left_joint{i}" for i in range(1, 7)]
_ARTICULATION = None
_LEFT_WRIST_VIEW = None
_LEFT_FINGER_A_VIEW = None
_LEFT_FINGER_B_VIEW = None
_R_LINK6_TCP = np.eye(3, dtype=float)
_P_LINK6_TCP = np.zeros(3, dtype=float)


def articulation_dof_indices(names):
    dof_names = list(_ARTICULATION.dof_names)
    return np.asarray([dof_names.index(name) for name in names], dtype=np.int64)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--usd",
        default="/workspace/assets/scene.usd",
    )
    parser.add_argument(
        "--grasp-json",
        default="/workspace/grasp-pipeline/work/selected_grasp.json",
    )
    parser.add_argument("--target", nargs=3, type=float)
    parser.add_argument("--base", nargs=4, type=float, default=[0.15, -0.27, 0.315, math.pi])
    parser.add_argument("--lift", type=float, default=-0.60)
    parser.add_argument("--output", default="/tmp/left_arm_graspnet_ik.json")
    parser.add_argument("--max-iters", type=int, default=120)
    parser.add_argument(
        "--solver", choices=["least_squares", "dls"], default="least_squares"
    )
    parser.add_argument("--eps", type=float, default=1.0e-3)
    parser.add_argument("--position-weight", type=float, default=30.0)
    parser.add_argument("--approach-axis-weight", type=float, default=8.0)
    parser.add_argument("--opening-axis-weight", type=float, default=4.0)
    parser.add_argument("--joint-center-weight", type=float, default=0.005)
    parser.add_argument("--continuity-weight", type=float, default=0.05)
    parser.add_argument("--damping", type=float, default=1.0e-3)
    parser.add_argument("--max-step", type=float, default=0.045)
    parser.add_argument("--position-tol", type=float, default=0.008)
    parser.add_argument("--orientation-tol", type=float, default=0.15)
    parser.add_argument("--trajectory-position-tol", type=float, default=0.04)
    parser.add_argument("--trajectory-orientation-tol", type=float, default=0.20)
    parser.add_argument("--opening-axis-tol", type=float, default=0.35)
    # USD gripper joints place the finger center on link6 +Z and open along link6 X.
    parser.add_argument("--wrist-approach-axis", type=int, default=2, choices=[0, 1, 2])
    parser.add_argument("--wrist-opening-axis", type=int, default=0, choices=[0, 1, 2])
    # GraspNet API convention and the real-robot service use rotation[:, 0] as
    # the approaching vector; rotation[:, 1] is the jaw opening axis.
    parser.add_argument("--grasp-approach-axis", type=int, default=0, choices=[0, 1, 2])
    parser.add_argument("--grasp-opening-axis", type=int, default=1, choices=[0, 1, 2])
    parser.add_argument(
        "--apply-graspnet-to-ee-rotation",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Map GraspNet gripper frame G1 to the real end-effector frame G2 before IK.",
    )
    parser.add_argument(
        "--graspnet-to-ee-mode",
        choices=["right", "right_transpose", "left", "left_transpose"],
        default="right",
        help="How to compose the user-provided G1->G2 matrix with GraspNet rotation.",
    )
    parser.add_argument(
        "--tcp-extrinsic-json",
        default="/workspace/grasp-pipeline/config/tcp_extrinsic.json",
        help="JSON generated by read_left_tcp_extrinsic.py; used to compare IK orientation at the gripper TCP instead of link6.",
    )
    parser.add_argument("--pregrasp-distance", type=float, default=0.08)
    parser.add_argument("--retract-distance", type=float, default=0.10)
    parser.add_argument("--retract-lift", type=float, default=0.05)
    parser.add_argument("--use-previous-ik", action="store_true")
    parser.add_argument("--seed", nargs=6, type=float)
    parser.add_argument("--joint-reference", nargs=6, type=float)
    parser.add_argument("--max-joint-deviation-deg", type=float)
    parser.add_argument("--ee-reference-joints", nargs=6, type=float)
    parser.add_argument("--max-ee-angle-deg", type=float, default=30.0)
    parser.add_argument("--use-ee-reference-orientation", action="store_true")
    parser.add_argument(
        "--auto-gripper-symmetry",
        action=argparse.BooleanOptionalAction,
        default=True,
        help=(
            "Resolve the parallel-gripper 180-degree symmetry around the grasp "
            "approach axis by choosing the TCP orientation nearest the reference pose."
        ),
    )
    parser.add_argument("--search-base-lift", action="store_true")
    parser.add_argument("--base-x-offsets", default="0")
    parser.add_argument("--base-y-offsets", default="-0.06,0,0.06")
    parser.add_argument("--lift-offsets", default="-0.06,0,0.06")
    parser.add_argument("--search-max-iters", type=int, default=35)
    return parser.parse_args()


def parse_offsets(text):
    return [float(item.strip()) for item in text.split(",") if item.strip()]


def vec(path, stage):
    prim = stage.GetPrimAtPath(path)
    if not prim.IsValid():
        raise RuntimeError(f"missing prim: {path}")
    p = UsdGeom.Xformable(prim).ComputeLocalToWorldTransform(Usd.TimeCode.Default()).ExtractTranslation()
    return np.array([float(p[0]), float(p[1]), float(p[2])], dtype=float)


def rotation_matrix(path, stage):
    prim = stage.GetPrimAtPath(path)
    if not prim.IsValid():
        raise RuntimeError(f"missing prim: {path}")
    m = UsdGeom.Xformable(prim).ComputeLocalToWorldTransform(Usd.TimeCode.Default())
    r = m.ExtractRotationMatrix()
    # Gf matrices compose row vectors; IK uses NumPy column vectors.
    return np.array(
        [[float(r[i][j]) for j in range(3)] for i in range(3)], dtype=float
    ).T


def normalize(v):
    n = float(np.linalg.norm(v))
    if n < 1.0e-9:
        return v
    return v / n


def rotation_angle_rad(a, b):
    delta = np.asarray(a, dtype=float).T @ np.asarray(b, dtype=float)
    trace = float(np.trace(delta))
    value = (trace - 1.0) * 0.5
    value = max(-1.0, min(1.0, value))
    return math.acos(value)


def graspnet_to_end_effector_rotation():
    # User-provided G1 -> G2 mapping:
    #   G1: GraspNet gripper frame
    #   G2: real PiPER/Isaac end-effector frame
    return np.array(
        [
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            [0.0, 1.0, 0.0],
        ],
        dtype=float,
    )


def apply_graspnet_to_ee_mapping(rotation, mapping, mode):
    if mode == "right":
        return rotation @ mapping
    if mode == "right_transpose":
        return rotation @ mapping.T
    if mode == "left":
        return mapping @ rotation
    if mode == "left_transpose":
        return mapping.T @ rotation
    raise ValueError(f"unsupported graspnet-to-ee mode: {mode}")


def set_robot_pose(stage, x, y, z, yaw):
    if _ARTICULATION is not None:
        position = np.asarray([[x, y, z]], dtype=np.float32)
        orientation = np.asarray(
            [[math.cos(0.5 * yaw), 0.0, 0.0, math.sin(0.5 * yaw)]],
            dtype=np.float32,
        )
        _ARTICULATION.set_world_poses(position, orientation, usd=False)
        _ARTICULATION.set_velocities(np.zeros((1, 6), dtype=np.float32))
        return
    xf = UsdGeom.Xformable(stage.GetPrimAtPath(ROBOT))
    ops = {op.GetOpName(): op for op in xf.GetOrderedXformOps()}
    (ops.get("xformOp:translate") or xf.AddTranslateOp()).Set(Gf.Vec3d(x, y, z))
    (ops.get("xformOp:rotateZ") or xf.AddRotateZOp()).Set(math.degrees(yaw))


def set_revolute(stage, joint_name, radians):
    prim = stage.GetPrimAtPath(f"{JOINTS}/{joint_name}")
    deg = math.degrees(float(radians))
    prim.GetAttribute("drive:angular:physics:targetPosition").Set(deg)
    state = prim.GetAttribute("state:angular:physics:position")
    if state and state.IsValid():
        state.Set(deg)


def set_prismatic(stage, joint_name, meters):
    if _ARTICULATION is not None:
        values = np.asarray([[float(meters)]], dtype=np.float32)
        indices = articulation_dof_indices([joint_name])
        _ARTICULATION.set_joint_positions(values, joint_indices=indices)
        _ARTICULATION.set_joint_velocities(
            np.zeros_like(values), joint_indices=indices
        )
        _ARTICULATION.set_joint_position_targets(values, joint_indices=indices)
        return
    prim = stage.GetPrimAtPath(f"{JOINTS}/{joint_name}")
    attr = prim.GetAttribute("drive:linear:physics:targetPosition")
    if attr and attr.IsValid():
        attr.Set(float(meters))
    state = prim.GetAttribute("state:linear:physics:position")
    if state and state.IsValid():
        state.Set(float(meters))


def set_left_arm(stage, q):
    if _ARTICULATION is not None:
        values = np.asarray([q], dtype=np.float32)
        indices = articulation_dof_indices(LEFT_ARM_JOINT_NAMES)
        _ARTICULATION.set_joint_positions(values, joint_indices=indices)
        _ARTICULATION.set_joint_velocities(
            np.zeros_like(values), joint_indices=indices
        )
        _ARTICULATION.set_joint_position_targets(values, joint_indices=indices)
        return
    for idx, value in enumerate(q, 1):
        set_revolute(stage, f"left_joint{idx}", value)


def settle(world, steps=1):
    for _ in range(steps):
        world.step(render=False)


def finger_center(stage):
    if _LEFT_WRIST_VIEW is not None:
        positions, _ = _LEFT_WRIST_VIEW.get_world_poses(clone=True, usd=False)
        wrist_position = np.asarray(positions[0], dtype=float)
    else:
        wrist_position = vec(LEFT_WRIST, stage)
    return wrist_position + current_wrist_rotation(stage) @ _P_LINK6_TCP


def current_wrist_rotation(stage):
    if _LEFT_WRIST_VIEW is not None:
        _, quaternions = _LEFT_WRIST_VIEW.get_world_poses(clone=True, usd=False)
        w, x, y, z = [float(v) for v in quaternions[0]]
        return np.array(
            [
                [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
                [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
                [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
            ],
            dtype=float,
        )
    return rotation_matrix(LEFT_WRIST, stage)


def current_tool_rotation(stage):
    return current_wrist_rotation(stage) @ _R_LINK6_TCP


def load_tcp_extrinsic(path):
    if not path:
        return np.eye(3, dtype=float), np.zeros(3, dtype=float), None
    p = Path(path)
    if not p.exists():
        print(f"tcp_extrinsic_missing {path}; using identity rotation", flush=True)
        return np.eye(3, dtype=float), np.zeros(3, dtype=float), None
    with p.open("r", encoding="utf-8") as f:
        data = json.load(f)
    rotation = np.asarray(data["link6_tcp"]["rotation_3x3"], dtype=float)
    u, _, vt = np.linalg.svd(rotation)
    rotation = u @ vt
    if np.linalg.det(rotation) < 0.0:
        u[:, -1] *= -1.0
        rotation = u @ vt
    translation = np.asarray(data["link6_tcp"]["translation_m"], dtype=float)
    return rotation, translation, data


def read_grasp(args):
    if args.target is not None:
        return np.array(args.target, dtype=float), None
    with open(args.grasp_json, "r", encoding="utf-8") as f:
        data = json.load(f)
    target = data.get("translation_world_xyz_m", data.get("translation_world"))
    if target is None:
        raise KeyError("grasp json must contain translation_world_xyz_m or translation_world")
    rotation = data.get("rotation_world_3x3", data.get("rotation_world"))
    return np.array(target, dtype=float), (np.array(rotation, dtype=float) if rotation is not None else None)


def clamp_to_limits(q, limits, margin=0.02, joint_reference=None, max_joint_deviation=None):
    out = np.array(q, dtype=float)
    for i, (lo, hi) in enumerate(limits):
        q_lo = lo + margin
        q_hi = hi - margin
        if joint_reference is not None and max_joint_deviation is not None:
            q_lo = max(q_lo, float(joint_reference[i]) - max_joint_deviation)
            q_hi = min(q_hi, float(joint_reference[i]) + max_joint_deviation)
        out[i] = float(np.clip(out[i], q_lo, q_hi))
    return out


def eval_state(stage, world, q):
    set_left_arm(stage, q)
    return finger_center(stage), current_tool_rotation(stage)


def numerical_jacobian(stage, world, q, p, wrist_rotation, args):
    j_pos = np.zeros((3, 6), dtype=float)
    j_approach = np.zeros((3, 6), dtype=float)
    j_opening = np.zeros((3, 6), dtype=float)
    approach = wrist_rotation[:, args.wrist_approach_axis]
    opening = wrist_rotation[:, args.wrist_opening_axis]
    q = np.array(q, dtype=float)
    for i in range(6):
        q2 = q.copy()
        q2[i] += args.eps
        p2, rotation2 = eval_state(stage, world, q2)
        j_pos[:, i] = (p2 - p) / args.eps
        j_approach[:, i] = (
            rotation2[:, args.wrist_approach_axis] - approach
        ) / args.eps
        j_opening[:, i] = (
            rotation2[:, args.wrist_opening_axis] - opening
        ) / args.eps
    eval_state(stage, world, q)
    return j_pos, j_approach, j_opening


def solve_seed_dls(stage, world, seed, target, target_rotation, args, limits, q_center, max_iters=None):
    joint_reference = (
        np.asarray(args.joint_reference, dtype=float)
        if args.joint_reference is not None
        else None
    )
    max_joint_deviation = (
        math.radians(args.max_joint_deviation_deg)
        if args.max_joint_deviation_deg is not None
        else None
    )
    q = clamp_to_limits(
        seed,
        limits,
        joint_reference=joint_reference,
        max_joint_deviation=max_joint_deviation,
    )
    q_start = q.copy()
    v_prev = np.zeros(6, dtype=float)
    best = None
    iters = args.max_iters if max_iters is None else int(max_iters)

    for it in range(iters):
        p, wrist_rotation = eval_state(stage, world, q)
        approach = wrist_rotation[:, args.wrist_approach_axis]
        opening = wrist_rotation[:, args.wrist_opening_axis]
        target_approach = target_rotation[:, args.grasp_approach_axis]
        target_opening = target_rotation[:, args.grasp_opening_axis]

        e_pos = target - p
        e_approach = target_approach - approach
        e_opening = target_opening - opening
        pos_err = float(np.linalg.norm(e_pos))
        approach_err = float(np.linalg.norm(e_approach))
        opening_err = float(np.linalg.norm(e_opening))
        orientation_err = (
            max(approach_err, opening_err)
            if args.opening_axis_weight > 0.0
            else approach_err
        )
        score = (
            pos_err
            + 0.12 * approach_err
            + (0.01 * opening_err if args.opening_axis_weight > 0.0 else 0.0)
            + 0.002 * float(np.linalg.norm(q - q_start))
            + 0.004 * float(np.linalg.norm(q - q_center))
        )
        if best is None or score < best["score"]:
            best = {
                "score": score,
                "iter": it,
                "q": q.copy(),
                "p": p.copy(),
                "rotation": wrist_rotation.copy(),
                "pos_err": pos_err,
                "approach_err": approach_err,
                "opening_err": opening_err,
                "orientation_err": orientation_err,
            }
        ee_angle = None
        ee_angle_ok = True
        if getattr(args, "ee_reference_rotation", None) is not None:
            ee_angle = rotation_angle_rad(args.ee_reference_rotation, wrist_rotation)
            if args.max_ee_angle_deg is not None:
                ee_angle_ok = ee_angle <= math.radians(args.max_ee_angle_deg)

        if (
            pos_err < args.position_tol
            and approach_err < args.orientation_tol
            and ee_angle_ok
            and (
                args.opening_axis_weight <= 0.0
                or opening_err < args.opening_axis_tol
            )
        ):
            break

        j_pos, j_approach, j_opening = numerical_jacobian(
            stage, world, q, p, wrist_rotation, args
        )
        rows = [math.sqrt(args.position_weight) * j_pos]
        rhs = [math.sqrt(args.position_weight) * e_pos]
        if args.approach_axis_weight > 0.0:
            rows.append(math.sqrt(args.approach_axis_weight) * j_approach)
            rhs.append(math.sqrt(args.approach_axis_weight) * e_approach)
        if args.opening_axis_weight > 0.0:
            rows.append(math.sqrt(args.opening_axis_weight) * j_opening)
            rhs.append(math.sqrt(args.opening_axis_weight) * e_opening)
        rows.append(math.sqrt(args.joint_center_weight) * np.eye(6))
        rhs.append(math.sqrt(args.joint_center_weight) * (q_center - q))
        rows.append(math.sqrt(args.continuity_weight) * np.eye(6))
        rhs.append(math.sqrt(args.continuity_weight) * v_prev)

        a = np.vstack(rows)
        b = np.concatenate(rhs)
        lhs = a.T @ a + args.damping * np.eye(6)
        dq = np.linalg.solve(lhs, a.T @ b)
        dq = np.clip(dq, -args.max_step, args.max_step)
        q = clamp_to_limits(
            q + dq,
            limits,
            joint_reference=joint_reference,
            max_joint_deviation=max_joint_deviation,
        )
        v_prev = dq

    p, wrist_rotation = eval_state(stage, world, best["q"])
    approach = wrist_rotation[:, args.wrist_approach_axis]
    opening = wrist_rotation[:, args.wrist_opening_axis]
    target_approach = target_rotation[:, args.grasp_approach_axis]
    target_opening = target_rotation[:, args.grasp_opening_axis]
    best["p"] = p.copy()
    best["rotation"] = wrist_rotation.copy()
    best["pos_err"] = float(np.linalg.norm(p - target))
    best["approach_err"] = float(np.linalg.norm(target_approach - approach))
    best["opening_err"] = float(np.linalg.norm(target_opening - opening))
    best["orientation_err"] = (
        max(best["approach_err"], best["opening_err"])
        if args.opening_axis_weight > 0.0
        else best["approach_err"]
    )
    best["ee_angle_from_reference_rad"] = None
    ee_angle_ok = True
    if getattr(args, "ee_reference_rotation", None) is not None:
        ee_angle = rotation_angle_rad(args.ee_reference_rotation, wrist_rotation)
        best["ee_angle_from_reference_rad"] = float(ee_angle)
        if args.max_ee_angle_deg is not None:
            ee_angle_ok = ee_angle <= math.radians(args.max_ee_angle_deg)
    best["converged"] = bool(
        best["pos_err"] < args.position_tol
        and best["approach_err"] < args.orientation_tol
        and ee_angle_ok
        and (
            args.opening_axis_weight <= 0.0
            or best["opening_err"] < args.opening_axis_tol
        )
    )
    best["score"] = (
        best["pos_err"]
        + 0.12 * best["approach_err"]
        + (
            0.01 * best["opening_err"]
            if args.opening_axis_weight > 0.0
            else 0.0
        )
        + 0.002 * float(np.linalg.norm(best["q"] - q_start))
        + 0.004 * float(np.linalg.norm(best["q"] - q_center))
    )
    return best


def solve_seed_least_squares(
    stage, world, seed, target, target_rotation, args, limits, q_center, max_iters=None
):
    joint_reference = (
        np.asarray(args.joint_reference, dtype=float)
        if args.joint_reference is not None
        else None
    )
    lower = np.asarray([item[0] for item in limits], dtype=float)
    upper = np.asarray([item[1] for item in limits], dtype=float)
    if joint_reference is not None and args.max_joint_deviation_deg is not None:
        deviation = math.radians(args.max_joint_deviation_deg)
        lower = np.maximum(lower, joint_reference - deviation)
        upper = np.minimum(upper, joint_reference + deviation)

    q_start = np.clip(np.asarray(seed, dtype=float), lower, upper)
    target_approach = target_rotation[:, args.grasp_approach_axis]
    target_opening = target_rotation[:, args.grasp_opening_axis]

    def residual(q):
        p, tool_rotation = eval_state(stage, world, q)
        rows = [math.sqrt(args.position_weight) * (target - p)]
        if args.approach_axis_weight > 0.0:
            rows.append(
                math.sqrt(args.approach_axis_weight)
                * (target_approach - tool_rotation[:, args.wrist_approach_axis])
            )
        if args.opening_axis_weight > 0.0:
            rows.append(
                math.sqrt(args.opening_axis_weight)
                * (target_opening - tool_rotation[:, args.wrist_opening_axis])
            )
        rows.append(math.sqrt(args.joint_center_weight) * (q_center - q))
        rows.append(math.sqrt(args.continuity_weight) * (q_start - q))
        if args.ee_reference_rotation is not None and args.max_ee_angle_deg is not None:
            angle = rotation_angle_rad(args.ee_reference_rotation, tool_rotation)
            excess = max(0.0, angle - math.radians(args.max_ee_angle_deg))
            rows.append(np.asarray([math.sqrt(20.0) * excess], dtype=float))
        return np.concatenate(rows)

    evaluations = (args.max_iters if max_iters is None else int(max_iters)) * 8
    result = least_squares(
        residual,
        q_start,
        bounds=(lower, upper),
        method="trf",
        jac="3-point",
        diff_step=args.eps,
        max_nfev=max(80, evaluations),
        xtol=1.0e-8,
        ftol=1.0e-8,
        gtol=1.0e-8,
    )
    q = np.asarray(result.x, dtype=float)
    p, tool_rotation = eval_state(stage, world, q)
    approach_err = float(
        np.linalg.norm(
            target_approach - tool_rotation[:, args.wrist_approach_axis]
        )
    )
    opening_err = float(
        np.linalg.norm(target_opening - tool_rotation[:, args.wrist_opening_axis])
    )
    pos_err = float(np.linalg.norm(target - p))
    ee_angle = (
        rotation_angle_rad(args.ee_reference_rotation, tool_rotation)
        if args.ee_reference_rotation is not None
        else None
    )
    ee_ok = (
        ee_angle is None
        or args.max_ee_angle_deg is None
        or ee_angle <= math.radians(args.max_ee_angle_deg)
    )
    opening_ok = args.opening_axis_weight <= 0.0 or opening_err < args.opening_axis_tol
    orientation_err = (
        max(approach_err, opening_err)
        if args.opening_axis_weight > 0.0
        else approach_err
    )
    score = (
        pos_err
        + 0.12 * approach_err
        + (0.01 * opening_err if args.opening_axis_weight > 0.0 else 0.0)
        + 0.002 * float(np.linalg.norm(q - q_start))
        + 0.004 * float(np.linalg.norm(q - q_center))
    )
    return {
        "score": score,
        "iter": int(result.nfev),
        "q": q,
        "p": p,
        "rotation": tool_rotation,
        "pos_err": pos_err,
        "approach_err": approach_err,
        "opening_err": opening_err,
        "orientation_err": orientation_err,
        "ee_angle_from_reference_rad": ee_angle,
        "converged": bool(
            pos_err < args.position_tol
            and approach_err < args.orientation_tol
            and opening_ok
            and ee_ok
        ),
    }


def solve_seed(stage, world, seed, target, target_rotation, args, limits, q_center, max_iters=None):
    if args.solver == "least_squares":
        return solve_seed_least_squares(
            stage,
            world,
            seed,
            target,
            target_rotation,
            args,
            limits,
            q_center,
            max_iters=max_iters,
        )
    return solve_seed_dls(
        stage,
        world,
        seed,
        target,
        target_rotation,
        args,
        limits,
        q_center,
        max_iters=max_iters,
    )


def solve_pose(stage, world, args, target, target_rotation, limits, q_center, seeds, base, lift, max_iters=None):
    set_robot_pose(stage, *base)
    set_prismatic(stage, "lifting_joint", lift)
    set_prismatic(stage, "left_joint7", 0.05)
    set_prismatic(stage, "left_joint8", -0.05)

    best = None
    seed_results = []
    for idx, seed in enumerate(seeds):
        result = solve_seed(stage, world, seed, target, target_rotation, args, limits, q_center, max_iters=max_iters)
        seed_results.append(
            {
                "seed_index": idx,
                "pos_err": result["pos_err"],
                "approach_err": result["approach_err"],
                "opening_err": result["opening_err"],
                "orientation_err": result["orientation_err"],
                "converged": result["converged"],
                "score": result["score"],
                "q": result["q"].tolist(),
            }
        )
        print(
            "seed_result",
            idx,
            "pos_err",
            result["pos_err"],
            "orientation_err",
            result["orientation_err"],
            "score",
            result["score"],
            flush=True,
        )
        if best is None or (not best["converged"], best["score"]) > (
            not result["converged"],
            result["score"],
        ):
            best = result
    return best, seed_results


def main():
    global _ARTICULATION, _LEFT_WRIST_VIEW, _LEFT_FINGER_A_VIEW, _LEFT_FINGER_B_VIEW
    global _R_LINK6_TCP, _P_LINK6_TCP
    args = parse_args()
    _R_LINK6_TCP, _P_LINK6_TCP, tcp_extrinsic = load_tcp_extrinsic(
        args.tcp_extrinsic_json
    )
    if tcp_extrinsic is not None:
        print(
            "tcp_extrinsic_loaded",
            args.tcp_extrinsic_json,
            "translation_m",
            tcp_extrinsic["link6_tcp"].get("translation_m"),
            flush=True,
        )
    target, rotation = read_grasp(args)
    if rotation is None:
        raise ValueError("GraspNet rotation_world is required for 6D grasp IK")
    target_rotation = np.asarray(rotation, dtype=float)
    # Remove small numerical drift introduced by camera-to-world conversion.
    u, _, vt = np.linalg.svd(target_rotation)
    target_rotation = u @ vt
    if np.linalg.det(target_rotation) < 0.0:
        u[:, -1] *= -1.0
        target_rotation = u @ vt
    graspnet_rotation = target_rotation.copy()
    r_g1_to_g2 = graspnet_to_end_effector_rotation()
    if args.apply_graspnet_to_ee_rotation:
        target_rotation = apply_graspnet_to_ee_mapping(
            target_rotation, r_g1_to_g2, args.graspnet_to_ee_mode
        )
        u, _, vt = np.linalg.svd(target_rotation)
        target_rotation = u @ vt
        if np.linalg.det(target_rotation) < 0.0:
            u[:, -1] *= -1.0
            target_rotation = u @ vt

    open_stage(args.usd)
    world = World(stage_units_in_meters=1.0)
    _ARTICULATION = world.scene.add(
        Articulation(prim_paths_expr=ROBOT, name="graspnet_ik_robot")
    )
    _LEFT_WRIST_VIEW = world.scene.add(
        RigidPrim(prim_paths_expr=LEFT_WRIST, name="graspnet_ik_left_wrist")
    )
    _LEFT_FINGER_A_VIEW = world.scene.add(
        RigidPrim(prim_paths_expr=LEFT_FINGER_A, name="graspnet_ik_left_finger_a")
    )
    _LEFT_FINGER_B_VIEW = world.scene.add(
        RigidPrim(prim_paths_expr=LEFT_FINGER_B, name="graspnet_ik_left_finger_b")
    )
    world.reset()
    stage = omni.usd.get_context().get_stage()

    limits = [
        (-2.61, 2.61),
        (0.0, 3.14),
        (-2.70, 0.0),
        (-1.83, 1.83),
        (-1.22, 1.22),
        (-3.14, 3.14),
    ]
    q_center = np.array([(lo + hi) * 0.5 for lo, hi in limits], dtype=float)
    seeds = [
        [-0.13, 1.38, -1.08, -1.60, -1.18, -0.13],
        [0.0, 0.8, -0.6, 0.0, 0.0, 0.0],
        [0.25, 0.9, -0.7, -0.35, 0.0, -0.8],
        [-0.25, 0.9, -0.7, 0.35, 0.0, 0.8],
        [0.45, 0.75, -0.55, -0.75, 0.0, -1.4],
        [0.0, 1.2, -0.9, 0.0, -0.2, 0.0],
        [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    ]
    if args.seed is not None:
        seeds.insert(0, list(args.seed))
    if args.use_previous_ik:
        previous_paths = [
            Path(args.output),
            Path("/tmp/left_arm_graspnet_ik.json"),
        ]
        for path in previous_paths:
            if path.exists():
                try:
                    with path.open("r", encoding="utf-8") as f:
                        old = json.load(f)
                    seeds.insert(0, old["q"][:6])
                    break
                except Exception:
                    pass

    args.ee_reference_rotation = None
    symmetry_flipped = False
    symmetry_angles_deg = None
    if args.ee_reference_joints is not None or args.max_ee_angle_deg is not None or args.use_ee_reference_orientation:
        reference_q = (
            np.asarray(args.ee_reference_joints, dtype=float)
            if args.ee_reference_joints is not None
            else np.zeros(6, dtype=float)
        )
        set_robot_pose(stage, *args.base)
        set_prismatic(stage, "lifting_joint", args.lift)
        _, reference_rotation = eval_state(stage, world, reference_q)
        args.ee_reference_rotation = reference_rotation.copy()
        print(
            "ee_reference_orientation",
            "joints",
            reference_q.tolist(),
            "max_angle_deg",
            args.max_ee_angle_deg,
            flush=True,
        )
        if args.use_ee_reference_orientation:
            target_rotation = reference_rotation.copy()
            print("using_ee_reference_orientation_as_ik_target", flush=True)
        elif args.auto_gripper_symmetry:
            symmetry = np.diag(
                [
                    1.0 if axis == args.grasp_approach_axis else -1.0
                    for axis in range(3)
                ]
            )
            flipped_rotation = target_rotation @ symmetry
            original_angle = rotation_angle_rad(reference_rotation, target_rotation)
            flipped_angle = rotation_angle_rad(reference_rotation, flipped_rotation)
            symmetry_angles_deg = [
                float(math.degrees(original_angle)),
                float(math.degrees(flipped_angle)),
            ]
            if flipped_angle < original_angle:
                target_rotation = flipped_rotation
                symmetry_flipped = True
            print(
                "gripper_symmetry",
                "reference_angles_deg",
                symmetry_angles_deg,
                "flipped",
                symmetry_flipped,
                flush=True,
            )

    search_results = []
    selected_base = list(args.base)
    selected_lift = float(args.lift)
    if args.search_base_lift:
        x_offsets = parse_offsets(args.base_x_offsets)
        y_offsets = parse_offsets(args.base_y_offsets)
        lift_offsets = parse_offsets(args.lift_offsets)
        quick_seeds = seeds[:4]
        search_best = None
        for dx in x_offsets:
            for dy in y_offsets:
                for dlift in lift_offsets:
                    candidate_base = [
                        float(args.base[0] + dx),
                        float(args.base[1] + dy),
                        float(args.base[2]),
                        float(args.base[3]),
                    ]
                    candidate_lift = float(args.lift + dlift)
                    print(
                        "base_lift_candidate",
                        "base",
                        candidate_base,
                        "lift",
                        candidate_lift,
                        flush=True,
                    )
                    candidate_best, _ = solve_pose(
                        stage,
                        world,
                        args,
                        target,
                        target_rotation,
                        limits,
                        q_center,
                        quick_seeds,
                        candidate_base,
                        candidate_lift,
                        max_iters=args.search_max_iters,
                    )
                    base_motion = math.hypot(dx, dy)
                    lift_motion = abs(dlift)
                    reach_score = (
                        candidate_best["pos_err"]
                        + 0.12 * candidate_best["approach_err"]
                        + (
                            0.02 * candidate_best["opening_err"]
                            if args.opening_axis_weight > 0.0
                            else 0.0
                        )
                        + 0.08 * base_motion
                        + 0.05 * lift_motion
                    )
                    record = {
                        "base": candidate_base,
                        "lift": candidate_lift,
                        "base_offset": [float(dx), float(dy), 0.0, 0.0],
                        "lift_offset": float(dlift),
                        "pos_err": candidate_best["pos_err"],
                        "orientation_err": candidate_best["orientation_err"],
                        "ik_score": candidate_best["score"],
                        "reach_score": reach_score,
                        "q": candidate_best["q"].tolist(),
                    }
                    search_results.append(record)
                    print(
                        "base_lift_result",
                        "pos_err",
                        record["pos_err"],
                        "orientation_err",
                        record["orientation_err"],
                        "reach_score",
                        reach_score,
                        flush=True,
                    )
                    if search_best is None or (
                        not candidate_best["converged"],
                        reach_score,
                    ) < (
                        not search_best["converged"],
                        search_best["reach_score"],
                    ):
                        record["converged"] = bool(candidate_best["converged"])
                        search_best = record
        selected_base = search_best["base"]
        selected_lift = search_best["lift"]
        seeds.insert(0, search_best["q"])
        print(
            "base_lift_selected",
            "base",
            selected_base,
            "lift",
            selected_lift,
            "reach_score",
            search_best["reach_score"],
            flush=True,
        )

    best, seed_results = solve_pose(
        stage,
        world,
        args,
        target,
        target_rotation,
        limits,
        q_center,
        seeds,
        selected_base,
        selected_lift,
    )

    q_best = best["q"]
    p_best, tool_rotation_best = eval_state(stage, world, q_best)
    grasp_approach = normalize(target_rotation[:, args.grasp_approach_axis])

    pregrasp_target = target - args.pregrasp_distance * grasp_approach
    pregrasp, pregrasp_seed_results = solve_pose(
        stage,
        world,
        args,
        pregrasp_target,
        target_rotation,
        limits,
        q_center,
        [q_best] + seeds,
        selected_base,
        selected_lift,
    )
    retract_target = (
        target
        - args.retract_distance * grasp_approach
        + np.array([0.0, 0.0, args.retract_lift], dtype=float)
    )
    retract, retract_seed_results = solve_pose(
        stage,
        world,
        args,
        retract_target,
        target_rotation,
        limits,
        q_center,
        [q_best, pregrasp["q"]] + seeds,
        selected_base,
        selected_lift,
    )
    max_ee_angle_rad = (
        math.radians(args.max_ee_angle_deg)
        if args.max_ee_angle_deg is not None
        else None
    )
    best_ee_angle = best.get("ee_angle_from_reference_rad")
    pregrasp_ee_angle = pregrasp.get("ee_angle_from_reference_rad")
    retract_ee_angle = retract.get("ee_angle_from_reference_rad")
    best_ee_ok = (
        True
        if max_ee_angle_rad is None or best_ee_angle is None
        else best_ee_angle <= max_ee_angle_rad
    )
    pregrasp_ee_ok = (
        True
        if max_ee_angle_rad is None or pregrasp_ee_angle is None
        else pregrasp_ee_angle <= max_ee_angle_rad
    )
    retract_ee_ok = (
        True
        if max_ee_angle_rad is None or retract_ee_angle is None
        else retract_ee_angle <= max_ee_angle_rad
    )
    pregrasp_ok = bool(
        pregrasp["pos_err"] < args.trajectory_position_tol
        and pregrasp["approach_err"] < args.trajectory_orientation_tol
        and (
            args.opening_axis_weight <= 0.0
            or pregrasp["opening_err"] < args.opening_axis_tol
        )
        and pregrasp_ee_ok
    )
    retract_ok = bool(
        retract["pos_err"] < args.trajectory_position_tol
        and retract["approach_err"] < args.trajectory_orientation_tol
        and (
            args.opening_axis_weight <= 0.0
            or retract["opening_err"] < args.opening_axis_tol
        )
        and retract_ee_ok
    )
    result = {
        "solver": args.solver,
        "scheme": "graspnet_position_plus_g1_to_g2_rotation_mapped_tool_axis",
        "converged": bool(best["converged"] and best_ee_ok),
        "distance_m": float(np.linalg.norm(p_best - target)),
        "orientation_error": float(best["orientation_err"]),
        "approach_axis_error": float(best["approach_err"]),
        "opening_axis_error": float(best["opening_err"]),
        "ee_angle_from_reference_deg": (
            None if best_ee_angle is None else float(math.degrees(best_ee_angle))
        ),
        "pregrasp_ee_angle_from_reference_deg": (
            None
            if pregrasp_ee_angle is None
            else float(math.degrees(pregrasp_ee_angle))
        ),
        "retract_ee_angle_from_reference_deg": (
            None
            if retract_ee_angle is None
            else float(math.degrees(retract_ee_angle))
        ),
        "q": [float(v) for v in q_best],
        "q_pregrasp": [float(v) for v in pregrasp["q"]],
        "q_grasp": [float(v) for v in q_best],
        "q_retract": [float(v) for v in retract["q"]],
        "trajectory_converged": {
            "pregrasp": pregrasp_ok,
            "grasp": bool(best["converged"]),
            "retract": retract_ok,
        },
        "trajectory_errors": {
            "pregrasp_position_m": float(pregrasp["pos_err"]),
            "pregrasp_approach_axis": float(pregrasp["approach_err"]),
            "retract_position_m": float(retract["pos_err"]),
            "retract_approach_axis": float(retract["approach_err"]),
        },
        "finger_center_world_xyz_m": [float(v) for v in p_best],
        "target_world_xyz_m": [float(v) for v in target],
        "pregrasp_target_world_xyz_m": [float(v) for v in pregrasp_target],
        "retract_target_world_xyz_m": [float(v) for v in retract_target],
        "graspnet_rotation_world_3x3": graspnet_rotation.tolist(),
        "graspnet_to_end_effector_rotation_3x3": r_g1_to_g2.tolist(),
        "graspnet_to_end_effector_mode": args.graspnet_to_ee_mode,
        "applied_graspnet_to_ee_rotation": bool(args.apply_graspnet_to_ee_rotation),
        "ik_target_rotation_world_3x3": target_rotation.tolist(),
        "gripper_symmetry_flipped": symmetry_flipped,
        "gripper_symmetry_reference_angles_deg": symmetry_angles_deg,
        "ee_reference_rotation_world_3x3": (
            None if args.ee_reference_rotation is None else args.ee_reference_rotation.tolist()
        ),
        "current_tool_rotation_world_3x3": tool_rotation_best.tolist(),
        "link6_to_tcp_rotation_3x3": _R_LINK6_TCP.tolist(),
        "link6_to_tcp_translation_m": (
            None
            if tcp_extrinsic is None
            else tcp_extrinsic["link6_tcp"].get("translation_m")
        ),
        "tcp_extrinsic_json": args.tcp_extrinsic_json,
        "target_approach_axis_world": [float(v) for v in grasp_approach],
        "base": [float(v) for v in selected_base],
        "lift": float(selected_lift),
        "weights": {
            "position": args.position_weight,
            "approach_axis": args.approach_axis_weight,
            "opening_axis": args.opening_axis_weight,
            "joint_center": args.joint_center_weight,
            "continuity": args.continuity_weight,
            "damping": args.damping,
            "max_step": args.max_step,
        },
        "axis_indices": {
            "left_wrist_approach_axis_index": args.wrist_approach_axis,
            "left_wrist_opening_axis_index": args.wrist_opening_axis,
            "graspnet_approach_axis_index": args.grasp_approach_axis,
            "graspnet_opening_axis_index": args.grasp_opening_axis,
        },
        "seed_results": seed_results,
        "pregrasp_seed_results": pregrasp_seed_results,
        "retract_seed_results": retract_seed_results,
        "base_lift_search": {
            "enabled": bool(args.search_base_lift),
            "base_x_offsets": parse_offsets(args.base_x_offsets),
            "base_y_offsets": parse_offsets(args.base_y_offsets),
            "lift_offsets": parse_offsets(args.lift_offsets),
            "search_max_iters": args.search_max_iters,
            "results": search_results,
        },
    }
    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2)
    print("LEFT_ARM_IK_RESULT " + json.dumps(result, indent=2), flush=True)
    app.close()


if __name__ == "__main__":
    main()
